name: CustomJoinItems
main: com.gmail.filoghost.customjoinitems.CustomJoinItems
version: 2.0

commands:
  customjoinitems:
    description: CustomJoinItems main command.
    usage: /<command>
    permission: customjoinitems.admin
    permission-message: You don't have permission.
    aliases: [cji]